### ISSUE TITLE
关于fine_loader中multi_label_flat索引的问题

### ISSUE THREAD

**Issue by Alieziar** [XpastaX/SoftFiNE#1]
作者您好，我在对您的代码复现时出现了fine_loader.py第66行处的报错：KeyError: 'multi_label_with_se_flat'，debug看了一下发现self.data[idx]中并未有这个标签，请问这个是标签是怎样生成的？
![5C0WZM(}$XIY CW{AUN7VKL](https://github.com/XpastaX/SoftFiNE/assets/60589888/76c79269-c7f7-4f96-88b0-fcdd1db86ea3)
![G6}41CAURI}L15 `KS0 _T](https://github.com/XpastaX/SoftFiNE/assets/60589888/634e7283-ec89-40be-aeac-3f291a1263e6)

**Comment by Alieziar** [comment]
继续看了一下，发现是在fine_process里有对这些标签的描述，但并没有提到有关multi_label相关的生成
![WG%MI_J~(W~M442}WU~0 UQ](https://github.com/XpastaX/SoftFiNE/assets/60589888/e1046969-f256-489e-8cc5-01f3d25e9d62)

**Comment by XpastaX** [comment]
> 继续看了一下，发现是在fine_process里有对这些标签的描述，但并没有提到有关multi_label相关的生成 ![WG%MI_J~(WM442}WU0 UQ](https://private-user-images.githubusercontent.com/60589888/290192396-e1046969-f256-489e-8cc5-01f3d25e9d62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTAzMDcsIm5iZiI6MTcxMzUxMDAwNywicGF0aCI6Ii82MDU4OTg4OC8yOTAxOTIzOTYtZTEwNDY5NjktZjI1Ni00ODllLThjYzUtMDFmM2QyNWU5ZDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYWUwOTA5OWFmYjFlNzRiNGQ0NTdmMThlOTNiZTMxNWI4MDc4Yjc2MDI3ZDE4NjRkZWY2NzYyNjQ3ZTQyMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D280H1sUdjsCK6VQpQVEvY_fVqocR4Nezk0CfOxFoB0)

可以把对应部分comment掉，这个应该是之前跑ranking baseline时做的标签，没有clean掉
